log4j.rootLogger=DEBUG, CLIENT
log4j.additivity.org.apache=true
log4j.handleQtMessages=true
log4j.appender.CLIENT=Log4Qt::RollingFileAppender
log4j.appender.CLIENT.ImmediateFlush=true
log4j.appender.CLIENT.AppendFile=true
log4j.appender.CLIENT.File=$PROGRAMDATA/log4qt_FirmwareUpdate.log
log4j.appender.CLIENT.MaxFileSize=10240KB
log4j.appender.CLIENT.MaxBackupIndex=50
log4j.appender.CLIENT.layout=Log4Qt::PatternLayout
log4j.appender.CLIENT.layout.ConversionPattern=<%p>%d [%t] %m %n